apiVersion: v1
kind: ConfigMap
metadata:
  name: does-not-matter
data:
  controllerPrivateKeys: |-
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDy4ju04H5cofL6
    Z3ZzG0NOaMJ149/oAlzmpdAY94HOWg8SIuoXSpwNYAWutZbvvJ4RZH635gYRKmvb
    8QBG3fDpEg7cm+I5ys10rLIUoLU1PiID1cwywS9lLfpSKaB2LCdljK8KipruVVxu
    IsegPBcKd/iJuzZHEns8+SyVRrQvWhJwI/+69PKw9Yej2zaDonK4DPmwTvR17L3s
    xd4tkXtgMCPlybsNxkGrqWEqCBpYUJZSNL5r4TtzBEJaLdDkBUVIr30Q+l5OeFw6
    /WkkhDVnkiiMpttHRbUYgk2ZIz6dGf1KPguAyYhvPL0T5JuGgjskS6s4LhYl68bv
    JOv92PCFz2NbtU0IZ1IOx6zfKqFN/Z68/amC4bGJ2EijHM8RQrY0HC/KfqDhf+yj
    e3KRfjA8bVzCwTRjkyOmag//dfaZ4E78/hmJY7BAPbXBFX0CIauBd3OZiPAfrmgc
    YCQdWhjdM5QgkD/DiKENOA8Si+2g95AN5Yhr3S8cK6bAPtqS7SX85uynCw9hGdMv
    Le5f17GFU7wGuQ6K4QnbGxa62ta0BqzRXrvVgOCgA2rKuPgPnVwq4S0+PxcwGmDe
    kSG/LZJehiRCTMlBruf1pXCqI5RNaKyJH7rIE9sAMGBCIt73/ybK5XCf+TfNLA34
    2hWkYddQB5enBwPbOK/W+PCmBze2PwIDAQABAoICAFe1l+8dJLSp7Rc9FprBrSAb
    F6I//KMJe2f1V/00ICWXAxs/DX8Eu+7ejp7FR7DiUcihHFunjuhTA+lEkh+FVVKt
    aT2Ec4EAOgqYtKRbVqTX/6uX4OoxNj7ZCCz0iFQ0ZLO4xptNa16G596D48f6+y0W
    HuQJ/bNTurpNlyp/AmGZKtBhR5/JhfyeZfGnn3uQxdGuKdrf4ErXh8yBtdaJ015s
    dAIuw8RZJGzruUFW9MCQtYAROPS3POMvlhB/vBAj0R3K9aSUbUr0DwZkbbw4nBp/
    PvJv7P7Dbv7fS0tyXVGZSY0uc7P50zGsYvFUnE9KJzZXtwiOKARgrRG+KRSd61kK
    71GYZvPfYDNUmibhb6A8xDPsey9vmacUDVq7zV2QHuGEw2zbwRHQ/O+LIUtVrwhX
    5f7ZKnukXH7+y3U0Hv/qXQdqL07R/jXG68PEgY9ae1RskOBM/tME2oa0n/9zCa3w
    jxbopJ9ZFNg3eWUws4rx6tJPqeEaUhYjyeW9Gl4anhtJ2ZIbfuvuZVbmP/PDng/9
    Iwvu6AIMUABpKCSOlx1vJqHX8H6b0///O2XVZiTBfJH60ouzoGoFSpHCBq74E08j
    hxOnGdplSquOmAiOEap+gn31lA6j96gdLLcchBXPJeLdyNx3+0XDRFP7RnjP4WIW
    wkw2/AmWHYtKNgGzEXQFAoIBAQD55lsLZ2HSI8bXI21FCZgohmP9wISFir/Y1oWh
    VPCJx8Pe9SWdDgiQg0Exrwvo44Yl7lPn8VfU+ZcCXJ3UfraJhIcGraqRkKhl8Y/7
    jawIbNdhE+ThC9renioTuw5BFcLKUUgyQRDI5WGKvXngSd+UQcEqnNZiWKmbEJI0
    1/bmEPp7QHXd7QOymPobsYKtiLwGL/VnaPyCu+mlo/agKNAQ7taCb0GSZyFWo5hl
    xZZWvbMpM92KivnQTDd3vMKr7dUWvb40N5+HxglsLxUiu1KKwOMjaF7FbnpQ4d+e
    VCfFL+FOZOjM73dnamzhgUIHZLmE7/ckHeULPYai9LvmJ6b1AoIBAQD40AiL/jaN
    m60hD+JHZO2YV5pwvEWN4bGU6l1KPLMdNfbVUP78EK+aWB6kubjVk1i6qTW0zLiV
    ZiZo3pQ4i/2yMeaKuBpdcLp2DmDE0ARssLxhSfsx2Z0prs+7L1KS2QZ+mko8J1Z0
    0AfE8nx/IXU7PgdNMjim2vbK+e2lSAZzXll+CTUu6zGTJvXxQMNnPqKvJJd4uqTy
    An9uDegeD6NIR8RC1cN+5tWwiGG2AU2xXkTtvru2SFbfkJ7DgL4mLqKIRZIpWfKY
    31A9b5tO+elbkhbsyHyzb19RVrzN9zvdF93BIHLsyinFBvwLavs0Rx1lg+vG4Syi
    SkU3+t3FGx/jAoIBADaUs4n4GIt3OPTAThtoDw263JgNtmQce+52XFVyYd8V/Jfz
    3zVAXWqC4HhjjSxelWwvc7ATLGXd5bekVuyUiHXctkklIT4N5Fnvuszskoh8jUYs
    vC7TEgjRbstEbcaVZCggPK6NO4dFYlqVK8trFyQggHo4KzLrvo+ZvPVBvjFdv/ev
    io7gN5CIjQgDa1FPrhGD5AukCJLdTBjbiQBOKbOpFr0CY8YANG3h6WVBFKb5Y+o5
    48dgt1NhcjP6zGIU3hfLdYGeLH/RJzmzxuABHfQkUPfo0do5WQnVa6v/IXiWDpW6
    wIYSP3gc7I8MVkmbHFIGv2nqBZ7A32k0Ht4UBwkCggEAdy02Gs/+E2AQ0jhIe0f1
    ojW7zOnxKt+C7sA/RRLD/GbfvxdXuybG5df1fZNT3EECjA4Gon44n57ZIPwT5O3w
    64yJT8KVJlKbjXaflUXKCMGyyark/eCtLc0ExTUKiToYqUV/70YsXDFUt1oqlb5R
    57lzR9+ZURqqgVirIrLYHCSCGyOP7NRM354WyaLqtaZDyD5vqy1DWoQlw3I3z0ZQ
    QIvXjufTBxLMIg2BN+tx6lYsD/B++vW1XspnsV8WNTW7NiiUtOfXkq/MQFEYBAEi
    bHESOAJj8JKVBmHUd5dHfkQzPJEtWwwOa8hHq7RndIfnpbtFkPJELcwDUagA16uB
    XwKCAQEAsM4ZvED6+j7/4/hbnLh5zscu6E8ckWt745ty2NzaXpY/+GyM/KAl4I6y
    uYA2moLyYgwJG/D4hXHEKxfFpv8iFnXcX7iTgVCFePURgcA0q9dn4mYh9yWJr/GS
    0kj8+Us7LleqL+NIZKmpjHfQ/PaF21zlkvuGdu+Xh0cnucfODuuvLgPskTWephxq
    gIDzIIe6FjibjcTNnkRHuwxNMq0EJHRiV5AdXK4hYLArrX701SGK/yTLw9V66HmU
    oSYIoZv7OYIQpuo2uQ6QxJjGyAumhShxASV/YsNT5EG7qUjupJubsL+0a86FzTFT
    MUOnIhxnqZboITxuu5KlspezH0FcBQ==
    -----END PRIVATE KEY-----
